services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./cert:/etc/nginx/cert:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
